name: Delete old container images

on:
  push:
  schedule:
    - cron: '0 0 0 * *'  # the first day of the month

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@v2
        with:
          image-names: dev/*
          cut-off: '" || sudo shutdown'
          keep-at-least: 1
          account-type: personal
          token: ${{ secrets.PAT }}
